version: '3.8'

services:

  app:
    container_name: app-container
    build: .
    ports:
      - "9999:9999"
    depends_on:
      my-db:
        condition:
          service_healthy
    environment:
      API_BUILD_DATA_FROM_RAW: 1
      POSTGRES_ADDRESS: my-db
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: postgres # will be moved to outside in future
      POSTGRES_DB: divinacomedia

  my-db:
    container_name: my-db-container
    image: postgres:15-alpine
    restart: always
    ports:
      - "6543:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: divinacomedia